// <auto-generated />
using System;
using K_Akica.API.Contracts.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace K_Akica.API.Contracts.Migrations
{
    [DbContext(typeof(K_AkicaContext))]
    partial class K_AkicaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("K_Akica.API.Contracts.Models.FeedItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<TimeSpan>("Duration")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("('10:00:00')");

                    b.Property<bool>("Poop");

                    b.Property<int>("PooperId");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("Wizz");

                    b.HasKey("Id");

                    b.HasIndex("PooperId");

                    b.ToTable("FeedItems","dbo");
                });

            modelBuilder.Entity("K_Akica.API.Contracts.Models.Pooper", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Race")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Poopers","dbo");
                });

            modelBuilder.Entity("K_Akica.API.Contracts.Models.FeedItem", b =>
                {
                    b.HasOne("K_Akica.API.Contracts.Models.Pooper", "Pooper")
                        .WithMany("FeedItems")
                        .HasForeignKey("PooperId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
